# Generated by Django 4.0 on 2021-12-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Profesor',
        ),
    ]
