# Generated by Django 4.0 on 2021-12-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_alumnos_alumno_rename_profesores_profesor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='apellido',
            new_name='apellidoAlumno',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='edad',
            new_name='edadAlumno',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='nombre',
            new_name='nombreAlumno',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='nombre',
            new_name='nombreMateria',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='apellido',
            new_name='apellidoProf',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='nombre',
            new_name='nombreProf',
        ),
    ]
